\documentclass{beamer}
\usepackage{amsmath}

\usetheme{boxes}

\begin{document}
\SweaveOpts{concordance=TRUE}
\title{Slightly Less Simple Mosquito Modeling}
\author[Pearson]{Carl~A.~B.~Pearson}
\institute[University of Florida]{
Emerging Pathogens Institute, University of Florida
}
\frame{\titlepage}

\frame{
\frametitle{What's this talk really about?}
\begin{itemize}
\item expression with models,
\item simple analytical approaches,
\item a little dimensional analysis,
\item how to connect those with experiments, and
\item a little about work habits and tools
\end{itemize}
}

\frame{

\begin{figure}
\begin{center}
<<plotfig1,fig=TRUE,echo=FALSE>>=
periodT <- 366; omega <- 2*pi/periodT
monthDays<-c(31,29,31,30,31,30,31,31,30,31,30,31)
monthOffset<- -(rev(cumsum(monthDays)) + -periodT/2)
monthInset<- monthOffset + 15
fun <- function(x) { cos(omega*x) }
cplot <- function() {
plot(fun, xlim=c(-periodT/2,periodT/2), 
     xlab="",yaxt="n",xaxt="n",ylab="Mosquito Abundance",type="l",col="blue")
axis(side=1, at=c(monthOffset,periodT/2), labels=F)
axis(side=1, at=monthInset, labels=c("JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"),tick=F, cex.axis=0.7)
}
cplot()
@
\end{center}
\end{figure}

}

\frame{

\begin{figure}
\begin{center}
\includegraphics[width=0.8\textwidth]{insert.pdf}
\caption{Bicout et al. "Horse-, Bird-, and Human-Seeking Behavior and Seasonal Abundance of Mosquitos in a West Nile Virus Focus of Southern France". J. Med. Entomol. 43(5): 936-946 (2006)}
\end{center}
\end{figure}

}

\frame{
\frametitle{So, a Disconnect.}
Specifically, it is impossible to match features like peak population, total population over a year, and turnover rate with a functional form

$$
M(t) = C\sin(\omega t+\theta)
$$

\ldots and these features can be critical to predicting transmission dynamics, and thus planning interventions.
}

\frame{
\frametitle{Do Better, But Keep It Simple}
What's appealling about this trigonometric representation?  Simplicity:

\begin{itemize}
\item two parameters
\item no spatial features
\item ``easy'' analytical form
\end{itemize}

Possible to identify alternatives that {\em can} match salient features, but still retain these features?
}

\frame{
What are those salient features?
}

\frame{
\begin{itemize}
\item every year,
\item over a relatively short duration,
\item the mosquito population rapidly increases,
\item sits at a high level of activity,
\item then rapidly declines,
\item apparently connected with resource availability \&\ environmental suitability
\end{itemize}
}

\frame{
What's present in the trigonometric formulation?
\begin{itemize}
\item every year, {\bf CHECK!} \ldots {\em but not the rest of:}
\item over a relatively short duration,
\item the mosquito population rapidly increases,
\item sits at a high level of activity,
\item then rapidly declines,
\item apparently connected with resource availability \&\ environmental suitability
\end{itemize}
}

\frame{

}


\frame{
\title{Engineering \&\ Maths Refresher, I}
\begin{enumerate}
\item useful to write models in terms of measurable parameters,
\item measurable parameters are not scale-free,
\item mathematics is more useful when scale free, therefore
\item dimensional analysis is awesome
\end{enumerate}
}

% \frame{
% where $M(t)$ is mosquito population w.r.t time
% \begin{align*}
% \dot{M(t)} = E(t) - \lambda M(t)
% \end{align*}
% defined on $t\in(-T/2,T/2)$
% }
% 
% \frame{
% common usage is $M(t)\propto$ simple trigonometric
% 
% What salient observed features does that miss?
% 
% aside: why replace given $M(t)$ with given $\dot{M(t)}$?
% }
% 
% \frame{
% Salient features:
% \begin{itemize}
% \item short time with appreciable population
% % note: measure of pop. may be totally unreliable; however, trappable pop might good surrogate for active pop.
% \item even shorter time for population rise and fall
% \item low correlation with early and peak populations % accurate? provide comparison plots?
% \end{itemize}
% 
% Need a spike-like $E(t)$ to replicate these.  Candidates?
% }
% 
% \frame{
% Spike-like could be more formally $\delta$-function like.
% 
% So: use $\delta$-function approximations.
% }
% 
% \frame{
% TODO list approximate delta functions.
% }
% 
% \frame{
% What should we use for the shape parameters?
% 
% clue: want oranges-to-oranges comparisons between the options
% }
% 
% \frame{
% I chose to make mosquito total births equivalent
% 
% TODO $M_p$ equation
% 
% and then to apply a subjective ``constraint'' on $\Delta t$
% 
% TODO delta t stuff
% }
% 
% \frame{
% TODO list approximate delta functions with params in place
% }
% 
% \frame{
% Now everything is on the same scale, but rewind: don't have any of the convenience of having the same scale.
% 
% So: dimensional analysis.  What parameters should be eliminated?
% }

\frame{
\frametitle{Some Habits and Tools}
The general arrow of scientific work has been towards increased specialization and collaboration.

This presents a few challenges to getting work done.  The final specialist work product can be very intimidating to collaborators with other specialities, which can make a collaboration's skeptical review of their combined product difficult. That's on top of the pure mechanics of handling multiple people modifying the same ``thing''.
% I come from a background where all collaborators are responsible for the entire product, not just their narrowly focused piece
}

\end{document}